// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::{DateTime, NaiveDateTime};
use diesel::{Queryable, QueryId};

use diesel::{prelude::*};
use diesel::sql_types::Timestamp;
use serde::{Serialize, Deserialize};

#[derive(Queryable, Debug, QueryId)]
#[diesel(table_name = crate::schema::access_key)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct AccessKey {
    pub id: i64,
    pub app_id: String,
    pub secret: String,
    pub is_enabled: bool,
    pub is_deleted: bool,
    pub deleted_at: Option<Timestamp>,
    pub created_by: String,
    pub created_time: Timestamp,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<Timestamp>,
}

#[derive(Queryable, Debug)]
pub struct App {
    pub id: i64,
    pub app_id: String,
    pub name: String,
    pub org_id: String,
    pub org_name: String,
    pub owner_name: String,
    pub owner_email: String,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct AppNamespace {
    pub id: i64,
    pub name: String,
    pub app_id: String,
    pub format: String,
    pub is_public: bool,
    pub comment: String,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Audit {
    pub id: i64,
    pub entity_name: String,
    pub entity_id: i64,
    pub op_name: String,
    pub comment: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct AuditLog {
    pub id: i64,
    pub trace_id: String,
    pub span_id: String,
    pub parent_spend_id: Option<String>,
    pub follows_from_span_id: Option<String>,
    pub operator: String,
    pub op_type: String,
    pub op_name: String,
    pub description: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct AuditLogDataInfluence {
    pub id: i64,
    pub span_id: String/* TODO: unknown type Bpchar */,
    pub influence_entity_id: String,
    pub influence_entity_name: String,
    pub field_name: Option<String>,
    pub field_old_value: Option<String>,
    pub field_new_value: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Cluster {
    pub id: i64,
    pub name: String,
    pub app_id: String,
    pub parent_cluster_id: i64,
    pub comment: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Commit {
    pub id: i64,
    pub change_sets: String,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    pub comment: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct GrayReleaseRule {
    pub id: i64,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    pub branch_name: String,
    pub rules: Option<String>,
    pub release_id: i64,
    pub branch_status: Option<i16>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Instance {
    pub id: i64,
    pub app_id: String,
    pub cluster_name: String,
    pub data_center: String,
    pub ip: String,
    pub created_time: NaiveDateTime,
    pub last_modified_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct InstanceConfig {
    pub id: i64,
    pub instance_id: Option<i64>,
    pub config_app_id: String,
    pub config_cluster_name: String,
    pub config_namespace_name: String,
    pub release_key: String,
    pub release_delivery_time: Option<NaiveDateTime>,
    pub created_time: NaiveDateTime,
    pub last_modified_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Item {
    pub id: i64,
    pub namespace_id: i64,
    pub key: String,
    pub type_: i16,
    pub value: String,
    pub comment: Option<String>,
    pub line_num: Option<i64>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Namespace {
    pub id: i64,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct NamespaceLock {
    pub id: i64,
    pub namespace_id: i64,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Release {
    pub id: i64,
    pub release_key: String,
    pub name: String,
    pub comment: Option<String>,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    pub configurations: String,
    pub is_abandoned: bool,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct ReleaseHistory {
    pub id: i64,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    pub branch_name: String,
    pub release_id: i64,
    pub previous_release_id: i64,
    pub operation: i16,
    pub operation_context: String,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct ReleaseMessage {
    pub id: i64,
    pub message: String,
    pub last_modified_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ServerConfig {
    pub id: i64,
    pub key: String,
    pub cluster: String,
    pub value: String,
    pub comment: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<NaiveDateTime>,
    pub created_by: String,
    pub created_time: NaiveDateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct ServiceRegistry {
    pub id: i64,
    pub service_name: String,
    pub uri: String,
    pub cluster: String,
    pub metadata: String,
    pub created_time: NaiveDateTime,
    pub last_modified_time: NaiveDateTime,
}

