//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_moment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub topic: Option<String>,
    pub publisher_id: i64,
    pub publisher: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub like_counts: i64,
    pub comment_counts: i64,
    pub real_like_counts: i64,
    pub real_comment_counts: i64,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
    pub summary: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub img_urls: Option<String>,
    pub video_urls: Option<String>,
    pub is_top: Option<i16>,
    pub topping_time: Option<DateTime>,
    pub password: Option<String>,
    pub prev_duration: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
