//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_log_data_influence")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub span_id: String,
    pub influence_entity_id: String,
    pub influence_entity_name: String,
    pub field_name: Option<String>,
    pub field_old_value: Option<String>,
    pub field_new_value: Option<String>,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTime>,
    pub created_by: String,
    pub created_time: DateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
