//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instance_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub instance_id: Option<i64>,
    pub config_app_id: String,
    pub config_cluster_name: String,
    pub config_namespace_name: String,
    pub release_key: String,
    pub release_delivery_time: Option<DateTime>,
    pub created_time: DateTime,
    pub last_modified_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
