//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room_theme")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub layout: Option<String>,
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub main_page_logo: Option<String>,
    pub rich_text: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub background_image: Option<String>,
    pub notice_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notice_content: Option<String>,
    pub notice_btn_label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub warm_video: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub warm_img: Option<String>,
    pub login_page_logo: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub login_page_bgimage: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub swiper_content: Option<String>,
    pub swiper_speed: Option<i16>,
    pub del_flag: i16,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
