//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room_user_favorite")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub room_id: i64,
    pub user_id: i64,
    pub user_name: String,
    pub r#type: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub followed_id: Option<i64>,
    pub followed_user_id: Option<i64>,
    pub followed_user_name: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
