//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_forbidden_set")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub room_id: Option<i64>,
    pub forbidden_type: i16,
    pub enable: i16,
    pub r#type: Option<i16>,
    pub type_id: i64,
    pub begin_time: Option<String>,
    pub end_time: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
