//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_chat_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub room_id: i64,
    pub room_name: Option<String>,
    pub msg_type: String,
    pub channel_code: Option<String>,
    pub ws_msg_type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub user_id: i64,
    pub user_name: Option<String>,
    pub nick_name: Option<String>,
    pub r#type: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    pub parent_id: Option<i64>,
    pub parent_user_name: Option<String>,
    pub level_id: Option<i64>,
    pub level_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub level_avatar: Option<String>,
    pub dept_id: Option<i64>,
    pub dept_name: Option<String>,
    pub dept_indx: Option<i16>,
    pub cur_to_top: Option<String>,
    pub top_to_cur: Option<String>,
    pub lecturer_name: Option<String>,
    pub lecturer_level: Option<i16>,
    pub lecturer_card_no: Option<String>,
    pub client_ip: Option<String>,
    pub client_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_agent: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub status: i16,
    pub del_flag: i16,
    pub at_id: Option<i64>,
    pub at_user_id: Option<i64>,
    pub at_user_name: Option<String>,
    pub at_nick_name: Option<String>,
    pub at_type: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub at_avatar: Option<String>,
    pub at_parent_id: Option<i64>,
    pub at_parent_user_name: Option<String>,
    pub at_level_id: Option<i64>,
    pub at_level_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub at_level_avatar: Option<String>,
    pub at_dept_id: Option<i64>,
    pub at_dept_name: Option<String>,
    pub at_dept_indx: Option<i16>,
    pub at_cur_to_top: Option<String>,
    pub at_top_to_cur: Option<String>,
    pub at_lecturer_name: Option<String>,
    pub at_lecturer_level: Option<i16>,
    pub at_lecturer_card_no: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub at_content: Option<String>,
    pub real_user_id: Option<i64>,
    pub real_user_name: Option<String>,
    pub real_nick_name: Option<String>,
    pub real_type: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub real_avatar: Option<String>,
    pub real_parent_id: Option<i64>,
    pub real_parent_user_name: Option<String>,
    pub real_level_id: Option<i64>,
    pub real_level_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub real_level_avatar: Option<String>,
    pub real_dept_id: Option<i64>,
    pub real_dept_name: Option<String>,
    pub real_cur_to_top: Option<String>,
    pub real_top_to_cur: Option<String>,
    pub real_lecturer_name: Option<String>,
    pub real_lecturer_level: Option<i16>,
    pub real_lecturer_card_no: Option<String>,
    pub as_type: Option<String>,
    pub msg_category: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
