//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room_chapter_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chapter_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub common: Option<String>,
    pub start_time: Time,
    pub end_time: Time,
    pub r#type: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    pub status: i16,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
