//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room_watch_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub action_type: String,
    pub room_id: i64,
    pub room_name: String,
    pub channel_code: String,
    pub user_id: i64,
    pub user_name: String,
    pub nick_name: Option<String>,
    pub parent_id: Option<i64>,
    pub parent_user_name: Option<String>,
    pub r#type: Option<i16>,
    pub level_id: Option<i64>,
    pub level_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub level_avatar: Option<String>,
    pub lecturer_name: Option<String>,
    pub lecturer_level: Option<i16>,
    pub lecturer_card_no: Option<String>,
    pub dept_id: Option<i64>,
    pub dept_name: Option<String>,
    pub dept_indx: Option<i16>,
    pub cur_to_top: Option<String>,
    pub top_to_cur: Option<String>,
    pub client_ip: Option<String>,
    pub client_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_agent: Option<String>,
    pub action: Option<String>,
    pub action_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
