//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub domain: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub decs: Option<String>,
    pub channel_code: Option<String>,
    pub allow_speech: Option<i16>,
    pub status: i16,
    pub indx: i16,
    pub theme_id: Option<i64>,
    pub theme_name: Option<String>,
    pub need_pswd: Option<i16>,
    pub live_pswd: Option<String>,
    pub is_guest_login: i16,
    pub is_team_admin: i16,
    pub is_virtual_msg: i16,
    pub short_msgs: Option<String>,
    pub like_counts: Option<i64>,
    pub favorites_counts: Option<i64>,
    pub comment_counts: Option<i64>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub remote_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
