//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_room_chapter_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub room_id: i64,
    pub room_name: String,
    pub channel_id: i64,
    pub channel_code: String,
    pub channel_name: String,
    pub chapter_id: i64,
    pub chapter_name: String,
    pub chapter_item_id: Option<i64>,
    pub chapter_item_name: Option<String>,
    pub lecturer_id: Option<i64>,
    pub lecturer_code: Option<String>,
    pub lecturer_name: Option<String>,
    pub date: Option<Date>,
    pub begin_time: Option<Time>,
    pub end_time: Option<Time>,
    pub live_status: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub push_flow_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pull_flow_url: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
