//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media_params")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub channel_id: Option<i64>,
    pub code: Option<String>,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub decs: Option<String>,
    pub status: i16,
    pub indx: Option<i16>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
