//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media_push_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub usrargs: Option<String>,
    pub action: String,
    pub app: String,
    pub appname: String,
    pub push_id: String,
    pub ip: Option<String>,
    pub node: Option<String>,
    pub height: Option<String>,
    pub width: Option<String>,
    pub created_time: DateTime,
    pub updated_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
