//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media_channel")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub decs: Option<String>,
    pub image: Option<String>,
    pub live_status: Option<i16>,
    pub status: i16,
    pub indx: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub push_flow_url: Option<String>,
    pub push_url_update_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pull_flow_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pull_flow_mobile_url: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
