//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "release")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub release_key: String,
    pub name: String,
    pub comment: Option<String>,
    pub app_id: String,
    pub cluster_name: String,
    pub namespace_name: String,
    #[sea_orm(column_type = "Text")]
    pub configurations: String,
    pub is_abandoned: bool,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTime>,
    pub created_by: String,
    pub created_time: DateTime,
    pub last_modified_by: Option<String>,
    pub last_modified_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
