//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_user_ws_log_statics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ref_id: Option<i64>,
    pub minutes_level_date: Option<String>,
    pub is_online: i16,
    pub year: String,
    pub month: String,
    pub day: String,
    pub hour: String,
    pub minute: Vec<String>,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
