//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub menu_id: i64,
    pub menu_name: String,
    pub parent_id: Option<i64>,
    pub order_num: Option<i16>,
    pub path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub component: Option<String>,
    pub component_name: Option<String>,
    pub query: Option<String>,
    pub is_frame: Option<i16>,
    pub is_cache: Option<i16>,
    pub menu_type: Option<String>,
    pub visible: Option<i16>,
    pub status: Option<i16>,
    pub perms: Option<String>,
    pub icon: Option<String>,
    pub created_by: Option<i64>,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
