//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_user_ws_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ws_session_type: Option<String>,
    pub room_id: Option<i64>,
    pub room_name: Option<String>,
    pub channel_code: Option<String>,
    pub user_id: i64,
    pub user_name: String,
    pub nick_name: String,
    pub r#type: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    pub parent_id: Option<i64>,
    pub parent_user_name: Option<String>,
    pub level_id: Option<i64>,
    pub level_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub level_avatar: Option<String>,
    pub lecturer_name: Option<String>,
    pub lecturer_level: Option<i16>,
    pub lecturer_card_no: Option<String>,
    pub dept_id: Option<i64>,
    pub dept_name: Option<String>,
    pub dept_indx: Option<i16>,
    pub cur_to_top: Option<String>,
    pub top_to_cur: Option<String>,
    pub login_time: DateTime,
    pub logout_time: Option<DateTime>,
    pub heart_beat_time: Option<DateTime>,
    pub split_time: Option<DateTime>,
    pub status: i16,
    pub del_flag: i16,
    pub client_ip: Option<String>,
    pub client_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
