//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_group_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub group_id: i64,
    #[sea_orm(primary_key)]
    pub user_id: i64,
    pub is_admin: i16,
    pub forbidden_chat: i16,
    pub user_nick_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
