//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_oper_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub oper_id: i64,
    pub title: Option<String>,
    pub business_type: Option<i16>,
    pub method: Option<String>,
    pub request_method: Option<String>,
    pub operator_type: Option<i16>,
    pub oper_name: Option<String>,
    pub dept_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub oper_url: Option<String>,
    pub oper_ip: Option<String>,
    pub oper_location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub oper_param: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub json_result: Option<String>,
    pub status: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub oper_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
