//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_sign_on")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub module: i16,
    pub module_id: Option<i64>,
    pub module_name: Option<String>,
    pub channel_code: Option<String>,
    pub sign_on_time: DateTime,
    pub user_name: Option<String>,
    pub nick_name: Option<String>,
    pub r#type: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    pub parent_id: Option<i64>,
    pub parent_user_name: Option<String>,
    pub level_id: Option<i64>,
    pub level_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub level_avatar: Option<String>,
    pub dept_id: Option<i64>,
    pub dept_name: Option<String>,
    pub dept_indx: Option<i16>,
    pub cur_to_top: Option<String>,
    pub top_to_cur: Option<String>,
    pub client_ip: Option<String>,
    pub client_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_agent: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
