//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_dict_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub dict_code: i64,
    pub dict_sort: Option<i16>,
    pub dict_label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub dict_value: Option<String>,
    pub dict_type: String,
    pub css_class: Option<String>,
    pub list_class: Option<String>,
    pub is_default: Option<i16>,
    pub status: Option<i16>,
    pub created_by: Option<i64>,
    pub created_time: DateTime,
    pub updated_by: Option<i64>,
    pub updated_time: DateTime,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
