//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_job")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub job_id: i64,
    #[sea_orm(primary_key)]
    pub job_name: String,
    #[sea_orm(primary_key)]
    pub job_group: String,
    pub invoke_target: String,
    pub cron_expression: Option<String>,
    pub misfire_policy: Option<String>,
    pub concurrent: Option<String>,
    pub status: Option<String>,
    pub created_by: Option<i64>,
    pub created_time: Option<DateTime>,
    pub updated_by: Option<i64>,
    pub updated_time: Option<DateTime>,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
