//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_notice")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub notice_id: i64,
    pub notice_title: String,
    pub notice_type: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub notice_content: Option<String>,
    pub status: Option<i16>,
    pub module: Option<i16>,
    pub module_id: Option<i64>,
    pub news_type: i16,
    pub from_user_id: Option<i64>,
    pub from_user_name: Option<String>,
    pub from_user_nick: Option<String>,
    pub to_user_id: Option<i64>,
    pub to_user_name: Option<String>,
    pub to_user_nick: Option<String>,
    pub remark: Option<String>,
    pub created_by: i64,
    pub created_time: DateTime,
    pub updated_by: i64,
    pub updated_time: DateTime,
    pub del_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
