//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_dept")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub dept_id: i64,
    pub parent_id: Option<i64>,
    pub parent_name: Option<String>,
    pub ancestors: Option<String>,
    pub dept_name: Option<String>,
    pub order_num: Option<i32>,
    pub leader: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub account_prefix: Option<String>,
    pub account_seq: Option<i64>,
    pub status: Option<i16>,
    pub del_flag: Option<i16>,
    pub created_by: Option<i64>,
    pub created_time: DateTime,
    pub updated_by: Option<i64>,
    pub updated_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
