//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_logininfor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub info_id: i64,
    pub user_id: Option<i64>,
    pub user_name: String,
    pub ipaddr: Option<String>,
    pub login_location: Option<String>,
    pub browser: Option<String>,
    pub os: Option<String>,
    pub status: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub msg: Option<String>,
    pub login_time: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent_str: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
